FamilyTrackerAuth/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('LoginRegister.urls')),
    path('admin/', admin.site.urls),
    path('events/', include('events.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path('fitness/', include('fitness.urls')),
    path('calendar/', include('calendar10.urls')),
    path('transactions/', include('transactions.urls')),
    path('familytracks/', include('familytracks.urls')),
    path('cal/', include('cal.urls')),
    path('administration/', include('administration.urls')),
    path('listsplan/', include('listsplan.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LoginRegister/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views
from .forms import LoginForm
from django.contrib import admin

app_name = 'LoginRegister'

urlpatterns = [
    path('LoginRegister/', views.LoginRegister, name='LoginRegister'),
    path('', views.FTMainMenu, name='FTMainMenu'),
    # path('LoginRegister/FTFinances/', views.FTFinances, name='FTFinances'),
    # path('cashinacctm/update/<int:pk>/', views.cashinacctm_update, name='cashinacctm_update'),
    # path('cashinacctm/delete/<int:pk>/', views.cashinacctm_delete, name='cashinacctm_delete'),
    path('LoginRegister/FTCalendar/', views.FTCalendar, name='FTCalendar'),
    path('LoginRegister/FTToDos/', views.FTToDos, name='FTToDos'),
    # path('LoginRegister/FTListChores/<int:listheader_id>/', views.FTListChores, name='FTListChores'),
    # path('listHeader/delete/<int:pk>/', views.listHeader_delete, name='listHeader_delete'),
    # path('listDetail/delete/<int:pk>/', views.listDetail_delete, name='listDetail_delete'),
    path('LoginRegister/FTFamilyTracks/', views.FTFamilyTracks, name='FTFamilyTracks'),
    path('LoginRegister/FTFitnessSports/', views.FTFitnessSports, name='FTFitnessSports'),
    path('LoginRegister/FTGrocery/', views.FTGrocery, name='FTGrocery'),
    path('LoginRegister/FTAcministration/', views.FTAcministration, name='FTAcministration'),
    path('LoginRegister/login/', auth_views.LoginView.as_view(template_name='FTperson_login.html', authentication_form=LoginForm), name='login'),
    path('LoginRegister/FTFinancesMenu/', views.FTFinancesMenu, name='FTFinancesMenu'),
    path('LoginRegister/FTFinMenu/', views.FTFinMenu, name='FTFinMenu'),
    path('LoginRegister/FTDefAcctsMenu/', views.FTDefAcctsMenu, name='FTDefAcctsMenu'),
    # path('LoginRegister/FTRevenueAccts/', views.FTRevenueAccts, name='FTRevenueAccts'),
    # path('financesacct_update/update/<int:pk>/', views.financesacct_update, name='financesacct_update'),
    # path('listHeader_update/update/<int:pk>/', views.listHeader_update, name='listHeader_update'),
    # path('listDetail_update/update/<int:pk>/', views.listDetail_update, name='listDetail_update'),
    # path('cashinacctm/delete/<int:pk>/', views.cashinacctm_delete, name='cashinacctm_delete'),
    # path('LoginRegister/FTExpAccts/', views.FTExpAccts, name='FTExpAccts'),
    # path('cashoutacctm/update/<int:pk>/', views.cashoutacctm_update, name='cashoutacctm_update'),
    # path('cashoutacctm/delete/<int:pk>/', views.cashoutacctm_delete, name='cashoutacctm_delete'),
    # path('LoginRegister/FTAssetAccts/', views.FTAssetAccts, name='FTAssetAccts'),
    # path('assetacctm/update/<int:pk>/', views.assetacctm_update, name='assetacctm_update'),
    path('assetacctm/delete/<int:pk>/', views.assetacctm_delete, name='assetacctm_delete'),
    # path('LoginRegister/FTLiabAccts/', views.FTLiabAccts, name='FTLiabAccts'),
    # path('liabacctm/update/<int:pk>/', views.liabacctm_update, name='liabacctm_update'),
    # path('liabacctm/delete/<int:pk>/', views.liabacctm_delete, name='liabacctm_delete'),                                                             
    # path('LoginRegister/FTEquityAccts/', views.FTEquityAccts, name='FTEquityAccts'),
    # path('equityacctm/update/<int:pk>/', views.equityacctm_update, name='equityacctm_update'),
    # path('equityacctm/delete/<int:pk>/', views.equityacctm_delete, name='equityacctm_delete'),
    path('LoginRegister/FTAcctGroupings/', views.FTAcctGroupings, name='FTAcctGroupings'),
    path('LoginRegister/FTGroupingDrillDown/', views.FTGroupingDrillDown, name='FTGroupingDrillDown'),
    path('LoginRegister/FTAccountDrillDown/', views.FTAccountDrillDown, name='FTAccountDrillDown'),
    path('LoginRegister/FTFamilySecurity/', views.FTFamilySecurity, name='FTFamilySecurity'),
    path('LoginRegister/FTApple/', views.FTApple, name='FTApple'),
    path('LoginRegister/FTAndroid/', views.FTAndroid, name='FTAndroid'),
    path('LoginRegister/FTSponRateTbl/', views.FTSponRateTbl, name='FTSponRateTbl'),
    # path('LoginRegister/FTTransactions/<int:batch_id>', views.FTTransactions, name='FTTransactions'),
    # path('LoginRegister/FTTransactions/', views.FTTransactions, name='FTTransactionsNoId'),
    # path('transactions/delete/<int:pk>/', views.transaction_delete, name='transaction_delete'),
    path('admin/', admin.site.urls),
    path('logout_user/', views.logout_user, name='logout'),
    path('LoginRegister/mainlandingpage/', views.mainlandingpage, name='mainlandingpage')
]

cal/urls.py
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.event, name='event_new'),
    path('event/edit/<int:event_id>/', views.event, name='event_edit'),
]

transactions/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'transactions'

urlpatterns = [
    path('', views.home, name="home"),
    path('main_landing_page/', views.main_landing_page, name='main_landing_page'),
    path('income_accts', views.income_accts, name='income_accts'),
    path('cashinacctm/update/<int:pk>/', views.cashinacctm_update, name='cashinacctm_update'),
    path('cashinacctm/delete/<int:pk>/', views.cashinacctm_delete, name='cashinacctm_delete'),
    path('show_construction', views.show_construction, name='show_construction'),
    path('accounts', views.accounts, name='accounts'),
    path('show_account/<int:account_id>', views.show_account, name='show_account'),
    path('search_accounts', views.search_accounts, name='search_accounts' ),
    path('statement-sectionsV/', views.StatementSectionsV, name='statement_section'),
    path('statement-sectionsV/<int:pk>/', views.StatementSectionsV, name='statement_section_with_id'),
    path('statement-sectionsV/delete/<int:pk>/', views.StatementSections_deleteV, name='section_delete'),
    path('statement-sectionsV/update/<int:pk>/', views.StatementSections_updateV, name="section_update"), # type: ignore
    path('statement/delete/<int:pk>/', views.Statement_deleteV, name='statement_delete'), # type: ignore
    path('statement/update/<int:pk>/', views.statement_update, name='statement_update'), # type: ignore
    path('statement-sectionsV/line/delete/<int:pk>/', views.SectionLines_deleteV, name='line_delete'),
    path('statement-sectionsV/line/update/<int:pk>/', views.SectionLines_updateV, name='line_update'),
    path('statement-sectionsV/account/delete/<int:pk>/', views.LineAccounts_deleteV, name='account_delete'),
    path('statement-sectionsV/account/update/<int:pk>/', views.LineAccounts_updateV, name='account_update'),
    path('statement-linesline/<int:listheader_id>/', views.SectionLinesV, name='statement_linesline'),
    path('statement-line-accountsV/delete/<int:pk>/', views.LineAccountsV, name='StatementLinesDetails_delete'),
    path('cash-flow-statement/', views.cash_flow_statement_view, name='cash_flow_statement'),
]

transactions/models.py
from django.db import models
from django.conf import settings

# #################################################
#     NEW STARTING 1/21
###################################################

# *******************************************************************************
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< PersonM >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# *******************************************************************************


class PersonM(models.Model):
    LocationID = models.IntegerField(null=True)
    firstname = models.CharField(max_length=255, null=True)
    lastname = models.CharField(max_length=255, null=True)
    MiddleName = models.CharField(max_length=255, null=True)
    Salutation = models.CharField(max_length=40, null=True)
    NameSuffix = models.CharField(max_length=120, null=True)
    Sex = models.CharField(max_length=40, null=True)
    EdDegree1 = models.CharField(max_length=40, null=True)
    EdMajor1 = models.CharField(max_length=80, null=True)
    EdDegree2 = models.CharField(max_length=40, null=True)
    EdMajor2 = models.CharField(max_length=80, null=True)
    DateJoinedTracker = models.DateField(auto_now_add=True)
    EmailPrimary = models.CharField(max_length=255, null=True)
    PostalCodePrimary = models.CharField(max_length=40, null=True)
    PhonePrimary = models.CharField(max_length=40, null=True)
    EmailSecondary = models.CharField(max_length=255, null=True)
    PostalCodeSecondary = models.CharField(max_length=40, null=True)
    PhoneSecondary = models.CharField(max_length=40, null=True)
    FTUserName = models.CharField(max_length=80, null=True)
    Password = models.CharField(max_length=255, null=True)

    class Meta:
        verbose_name_plural = 'Persons'

    def __str__(self):
        return self.firstname

# *******************************************************************************
# <<<<<<<<<<<<<<<<<<<<<<<<<<< Financial Statements >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# *******************************************************************************


class FinStatements(models.Model):
    FSPersonFK = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)
    FSName = models.CharField(max_length=240, default='')
    FSCurrentDate = models.DateField(auto_now_add=True)
    FSFromDate = models.DateField()
    FSThroughDate = models.DateField()
    FSPostedDate = models.DateField()

    def __str__(self):
        return self.FSName

# *******************************************************************************
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<< Statement Sections >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# *******************************************************************************


class StatementSections(models.Model):
    FinStatementsFK = models.ForeignKey(
        'FinStatements', null=True, blank=True, on_delete=models.CASCADE)
    SSPersonFK = models.ForeignKey(
        PersonM, null=True, on_delete=models.CASCADE)
    SSName = models.CharField(max_length=240, default='')
    SSDescription = models.CharField(max_length=960, default='')

    def __str__(self):
        return self.SSName

# *******************************************************************************
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Section Lines >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# *******************************************************************************


class SectionLines(models.Model):
    SLStatementSectionsFK = models.ForeignKey(
        'StatementSections', null=True, blank=True, on_delete=models.CASCADE, related_name='statementsectionlines_set')
    SLPersonFK = models.ForeignKey(
        PersonM, null=True, on_delete=models.CASCADE)
    SLName = models.CharField(max_length=240)
    SLDescription = models.CharField(max_length=240)

    def __str__(self):
        return self.SLName

# *******************************************************************************
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Line Accounts >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# *******************************************************************************


class LineAccounts(models.Model):
    LAStatementLineFK = models.ForeignKey(
        'SectionLines', null=True, blank=True, on_delete=models.CASCADE, related_name='statementlineaccounts_set')
    LAPersonFK = models.ForeignKey(
        PersonM, null=True, on_delete=models.CASCADE)
    LAAccount = models.IntegerField()
    LAAccountType = models.CharField(max_length=12)
    LAADescription = models.CharField(max_length=240)

    def __str__(self):
        return self.LAAccount

# *******************************************************************************
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< CashInAcctM >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# *******************************************************************************


class CashInAcctM(models.Model):
    Status = models.CharField(max_length=10, null=True)
    AccountNumber = models.CharField(max_length=20, null=True)
    Description = models.CharField(max_length=255, null=True)
    Type = models.CharField(max_length=12, null=True)
    Sequence = models.IntegerField(null=True)
    RollupType = models.CharField(max_length=60, null=True)

    class Meta:
        verbose_name_plural = 'Accounts'

    def __str__(self):
        return self.AccountNumber

# *******************************************************************************
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< TransBatch >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# *******************************************************************************


class TransBatch(models.Model):
    TransBatchName = models.CharField(max_length=120, null=True, unique=True)
    TransBatchDate = models.DateField(null=True)
    Created = models.DateTimeField(auto_now_add=True)
    LastUpdated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.TransBatchName

    class Meta:
        verbose_name_plural = 'Transaction Batch'

# *******************************************************************************
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< TransHeader >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# *******************************************************************************


class TransHeader(models.Model):
    TransBatchID = models.ForeignKey(
        'TransBatch', null=True, on_delete=models.CASCADE)
    TransDescription = models.CharField(max_length=120, null=True)
    TransDate = models.DateField(null=True)
    TransNote = models.CharField(max_length=240, null=True)
    Created = models.DateTimeField(auto_now_add=True)
    LastUpdated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Transaction Header'

    def __str__(self):
        return self.TransDescription

# *******************************************************************************
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< TransDetail >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# *******************************************************************************


class TransDetail(models.Model):
    TransHeaderID = models.ForeignKey(
        'TransHeader', null=True, on_delete=models.CASCADE)
    Amount = models.IntegerField()
    DrAccount = models.CharField(max_length=10, null=True)
    CrAccount = models.CharField(max_length=10, null=True)
    Created = models.DateTimeField(auto_now_add=True)
    LastUpdated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Transaction Detail'

    def __str__(self):
        return self.Amount

transactions/templates/transactions/FTAccountDrillDown.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Account Drill-Down{% endblock %}

{% block pageimage %}
<img style="float: left;" src="{% static 'AccountDrillDown .jpg' %}" alt="Account Drill-Down Tile missing" width="100" height="100">
{% endblock %}

{% block backurl %}{%url 'LoginRegister:FTDefAcctsMenu'%}{% endblock %}

        {% block content %}
          <div class="h1">
              <a style="color:rgb(6, 6, 192)">
                <p style="font-size:40px">
                  <h2>Account Drill-Down</h2>
                </p>
              </a>
          </div> 
        {% endblock %}
        

transactions/templates/transactions/FTAcctGroupings.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Account Groupings{% endblock %}

{% block pageimage %}
<img style="float: left;" src="{% static 'AccountGrouping.jpg' %}" alt="Grocery Tile missing" width="100" height="100">
{% endblock %}

{% block backurl %}{%url 'LoginRegister:FTDefAcctsMenu'%}{% endblock %}

        {% block content %}
          <div class="h1">
              <a style="color:rgb(6, 6, 192)">
                <p style="font-size:40px">
                  <h2>Account Groupings</h2>
                </p>
              </a>
          </div> 
        {% endblock %}
        

transactions/templates/transactions/FTAcministration.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Administration Menu{% endblock %}

{% block pageimage %}
<img style="float: left;" src="{% static 'Administration.jpg' %}" alt="Administration Menu Tile missing" width="100"
  height="100">
{% endblock %}
{% block backurl %}{%url 'LoginRegister:FTMainMenu'%}{% endblock %}

{% block pageTitle %}
<div class="h1">
  <a style="color:rgb(6, 6, 192)">
    <p style="font-size:40px">
      <h2>Administration Menu</h2>
    </p>
  </a>
</div>
{% endblock %}

{% block content %}
<br>
<br>
<p style="text-align:center">
  <a href="{% url 'LoginRegister:FTFamilySecurity' %}"><img src="{% static 'FamilySecurity.jpg' %}" alt="Family Security Tile Missing" width="130" height="130"></a>
  <a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp </a>
  <a href="{% url 'LoginRegister:FTApple' %}"><img src="{% static 'FamilyTrackerMobile.jpg' %}" alt="Apple Tile Missing" width="140" height="140"></a>
  <a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp </a>
  <!-- <a href="{% url 'LoginRegister:FTAndroid' %}"><img src="{% static 'Android.jpg' %}" alt="Android Tile Missing" width="130" height="130"></a> -->
  <!-- <a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp </a> -->
</p>
{% endblock %}

transactions/templates/transactions/FTRevenueAccts.html
{% extends 'transactions/base.html' %}
{% load static %}
{% load bootstrap_icons %}

{% block title %}Accounts{% endblock %}

{% block pageimage %}
<img style="float: left;" src="{% static 'Cashin.jpg' %}" alt="Cash In Tile Missing" width="100" height="100">
{% endblock %}

{% block backurl %}{%url 'LoginRegister:FTDefAcctsMenu'%}{% endblock %}
{% block pageTitle %}
{% endblock %}

{% block content %}
<center>
  <div class="h1">
    <a style="color:rgb(6, 6, 192)">
      <p style="font-size:40px">
        <h2>Accounts</h2>
      </p>
    </a>
  </div>
  </center>
  <div>
    <table>
      <thead>
        <tr>
          <th>Status</th>
          <th>Type</th>
          <th>Account</th>
          <th>Description</th>
          <th>Statment</th>
          <th>Section</th>
          <th>Rollup</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for cashinacctm in cashinacctms %}
        <tr>
          <td>{{ cashinacctm.Status }}</td>
          <td>{{ cashinacctm.Type }}</td>
          <td>{{ cashinacctm.AccountNumber }}</td>
          <td>{{ cashinacctm.Description }}</td>
          <td>{{ cashinacctm.Statement }}</td>
          <td>{{ cashinacctm.Section }}</td>
          <td>{{ cashinacctm.RollupType }}</td>
          <!-- KMS Added New Fields -->
          <td>
            <a href="{% url 'transactions:cashinacctm_delete' cashinacctm.id %}" class="delete-button">{% bs_icon 'trash' %}</a>
            <a href="#editModal" data-bs-toggle="modal" data-account-number="{{ cashinacctm.AccountNumber }}" 
            data-status="{{ cashinacctm.Status }}" data-type="{{ cashinacctm.Type }}" data-type="{{ cashinacctm.Statement }}" data-type="{{ cashinacctm.RollupType }}" data-type="{{ cashinacctm.Section }}" data-description="{{ cashinacctm.Description }}" data-cashinacctm-id="{{ cashinacctm.id }}"
              class="edit-header-button">{% bs_icon 'pencil' %}</a>
          </td>
        </tr>
        {% endfor %}
        <tr>
          <td colspan="8" class="text-center">
            <a class="add-button btn btn-info" href="#addModal" data-bs-toggle="modal">Add</a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <!-- Add modal -->
  <div class="modal fade" id="addModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="tutorial1Label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="tutorial1Label">Add</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{% url 'transactions:income_accts' %}" method="post" id="addForm">
            {% csrf_token %}
            <div class="form-group">
              <label for="{{ form.AccountNumber.id_for_label }}">Account Number</label>
              {{ form.AccountNumber }}
            </div>
            <div class="form-group">
              <label for="{{ form.Description.id_for_label }}">Description</label>
              {{ form.Description }}
            </div>
            {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
              {% for field in form %}
              {{ field.errors }}
              {% endfor %}
  
              {{ form.non_field_errors }}
            </div>
            {% endif %}
        </div>
        <div class="modal-footer">
          <button type="submit"
              class="btn btn-primary">Submit</button>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </form>
      </div>
    </div>
  </div>
  <!-- Edit modal -->
  <div class="modal fade" id="editModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="tutorial1Label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="tutorial1Label">Edit</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form method="post" id="editForm">
            {% csrf_token %}
            <div class="form-group">
              <label for="{{ form.Status.id_for_label }}">Status</label>
              {{ form.Status }}
            </div>
<!-- KMS -->
            <div class="form-group">
              <label for="{{ form.Type.id_for_label }}">Type</label>
              {{ form.Type }}
            </div>
<!-- KMS -->
            <div class="form-group">
              <label for="{{ form.AccountNumber.id_for_label }}">Account</label>
              {{ form.AccountNumber }}
            </div>
            <div class="form-group">
              <label for="{{ form.Description.id_for_label }}">Description</label>
              {{ form.Description }}
            </div>
<!-- KMS -->
            <div class="form-group">
              <label for="{{ form.Statement.id_for_label }}">Statement</label>
              {{ form.Statement }}
            </div>
            <div class="form-group">
              <label for="{{ form.Section.id_for_label }}">Section</label>
              {{ form.Section }}
            </div>
            <div class="form-group">
              <label for="{{ form.RollupType.id_for_label }}">Rollup</label>
              {{ form.Section }}
            </div>
<!-- KMS -->


            {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
              {% for field in form %}
                  {{ field.errors }}
              {% endfor %}
  
              {{ form.non_field_errors }}
            </div>
            {% endif %}
        </div>
        <div class="modal-footer">
          <button type="submit"
              class="btn btn-primary">Submit</button>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </form>
      </div>
    </div>
  </div>


{% endblock %}
{% block modal-script %}
<script>
  $(document).ready(function() {
    $('#editModal').on('show.bs.modal', function (event) {
    console.log('Modal is about to be shown.');
      var button = $(event.relatedTarget);
      var status = button.data('status');
      // KMS
      var type = button.data('type');
      var statement = button.data('statement');
      var section = button.data('section');
      // KMS
      var accountNumber = button.data('account-number');
      var description = button.data('description');
      var cashinacctmId = button.data('cashinacctm-id');
      
      var editForm = $('#editForm');
      console.log(editForm);
      var editUrl = "{% url 'transactions:cashinacctm_update' 0 %}".replace('0', cashinacctmId);
      editForm.attr('action', editUrl);
      var modal = $(this);
      // var accountNumber = modal.find('#id_AccountNumber').val();
      console.log(accountNumber);
      // var description = modal.find('#id_Description').val();

      // Dynamically update IDs
      editForm.find('#id_Status').attr('id', 'edit_Status');
// KMS
      editForm.find('#id_Type').attr('id', 'edit_Type');
      editForm.find('#id_Statement').attr('id', 'edit_Statement');
      editForm.find('#id_Section').attr('id', 'edit_Section');
      editForm.find('#id_RollupType').attr('id', 'edit_RollupType');
// kms
      editForm.find('#id_AccountNumber').attr('id', 'edit_AccountNumber');
      editForm.find('#id_Description').attr('id', 'edit_Description');

      // Set the values in the edit form
      var account = $('#edit_AccountNumber');
      var statusField = $('#edit_Status');
// KMS
      var typeField = $('#edit_Type');
      var statementField = $('#edit_Statement');
      var sectionField = $('#edit_Section');
      var rolluptypeField = $('#edit_RollupType');
// KMS
      console.log(account);
      var descriptionField = $('#edit_Description');

      account.val(accountNumber);
      statusField.val(status);
// KMS
      typeField.val(type);
      statementField.val(statement);
      sectionField.val(section);
      rolluptypeField.val(rolluptype)
// KMS
      descriptionField.val(description);
  });
});

</script>
{% endblock %}

transactions/templates/transactions/show_construction.html
{% extends 'transactions/base.html' %}
{% load static %}

{% block content %}
<p style="text-align:center">
  <div class="h1">
    <a style="color:rgb(6, 6, 192)">
      <p style="font-size:40px">
        <h2>Under Construction</h2>
        <!-- <img src="{% static 'construction.jpg' %}" style="height: 30%;" alt="Under Construction" -->
      </p>
    </a>
  </div>
</p>
</br></br>   
<div style="width: 100%; height: 250px; background-color: #DDEBF7;">
    <!-- <a href="#exampleModal" data-bs-toggle="modal"> -->
    <img src="{% static 'construction.jpg' %}" style="height: 100%;" alt="Under Construction">
    <!-- </a> -->
</div>

{% endblock %}