FamilyTrackerAuth/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('LoginRegister.urls')),
    path('admin/', admin.site.urls),
    path('events/', include('events.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path('fitness/', include('fitness.urls')),
    path('calendar/', include('calendar10.urls')),
    path('transactions/', include('transactions.urls')),
    path('familytracks/', include('familytracks.urls')),
    path('cal/', include('cal.urls')),
    path('administration/', include('administration.urls')),
    path('listsplan/', include('listsplan.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LoginRegister/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views
from .forms import LoginForm
from django.contrib import admin

app_name = 'LoginRegister'

urlpatterns = [
    path('LoginRegister/', views.LoginRegister, name='LoginRegister'),
    path('', views.FTMainMenu, name='FTMainMenu'),
    # path('LoginRegister/FTFinances/', views.FTFinances, name='FTFinances'),
    # path('cashinacctm/update/<int:pk>/', views.cashinacctm_update, name='cashinacctm_update'),
    # path('cashinacctm/delete/<int:pk>/', views.cashinacctm_delete, name='cashinacctm_delete'),
    path('LoginRegister/FTCalendar/', views.FTCalendar, name='FTCalendar'),
    path('LoginRegister/FTToDos/', views.FTToDos, name='FTToDos'),
    # path('LoginRegister/FTListChores/<int:listheader_id>/', views.FTListChores, name='FTListChores'),
    # path('listHeader/delete/<int:pk>/', views.listHeader_delete, name='listHeader_delete'),
    # path('listDetail/delete/<int:pk>/', views.listDetail_delete, name='listDetail_delete'),
    path('LoginRegister/FTFamilyTracks/', views.FTFamilyTracks, name='FTFamilyTracks'),
    path('LoginRegister/FTFitnessSports/', views.FTFitnessSports, name='FTFitnessSports'),
    path('LoginRegister/FTGrocery/', views.FTGrocery, name='FTGrocery'),
    path('LoginRegister/FTAcministration/', views.FTAcministration, name='FTAcministration'),
    path('LoginRegister/login/', auth_views.LoginView.as_view(template_name='FTperson_login.html', authentication_form=LoginForm), name='login'),
    path('LoginRegister/FTFinancesMenu/', views.FTFinancesMenu, name='FTFinancesMenu'),
    path('LoginRegister/FTFinMenu/', views.FTFinMenu, name='FTFinMenu'),
    path('LoginRegister/FTDefAcctsMenu/', views.FTDefAcctsMenu, name='FTDefAcctsMenu'),
    # path('LoginRegister/FTRevenueAccts/', views.FTRevenueAccts, name='FTRevenueAccts'),
    # path('financesacct_update/update/<int:pk>/', views.financesacct_update, name='financesacct_update'),
    # path('listHeader_update/update/<int:pk>/', views.listHeader_update, name='listHeader_update'),
    # path('listDetail_update/update/<int:pk>/', views.listDetail_update, name='listDetail_update'),
    # path('cashinacctm/delete/<int:pk>/', views.cashinacctm_delete, name='cashinacctm_delete'),
    # path('LoginRegister/FTExpAccts/', views.FTExpAccts, name='FTExpAccts'),
    # path('cashoutacctm/update/<int:pk>/', views.cashoutacctm_update, name='cashoutacctm_update'),
    # path('cashoutacctm/delete/<int:pk>/', views.cashoutacctm_delete, name='cashoutacctm_delete'),
    # path('LoginRegister/FTAssetAccts/', views.FTAssetAccts, name='FTAssetAccts'),
    # path('assetacctm/update/<int:pk>/', views.assetacctm_update, name='assetacctm_update'),
    path('assetacctm/delete/<int:pk>/', views.assetacctm_delete, name='assetacctm_delete'),
    # path('LoginRegister/FTLiabAccts/', views.FTLiabAccts, name='FTLiabAccts'),
    # path('liabacctm/update/<int:pk>/', views.liabacctm_update, name='liabacctm_update'),
    # path('liabacctm/delete/<int:pk>/', views.liabacctm_delete, name='liabacctm_delete'),                                                             
    # path('LoginRegister/FTEquityAccts/', views.FTEquityAccts, name='FTEquityAccts'),
    # path('equityacctm/update/<int:pk>/', views.equityacctm_update, name='equityacctm_update'),
    # path('equityacctm/delete/<int:pk>/', views.equityacctm_delete, name='equityacctm_delete'),
    path('LoginRegister/FTAcctGroupings/', views.FTAcctGroupings, name='FTAcctGroupings'),
    path('LoginRegister/FTGroupingDrillDown/', views.FTGroupingDrillDown, name='FTGroupingDrillDown'),
    path('LoginRegister/FTAccountDrillDown/', views.FTAccountDrillDown, name='FTAccountDrillDown'),
    path('LoginRegister/FTFamilySecurity/', views.FTFamilySecurity, name='FTFamilySecurity'),
    path('LoginRegister/FTApple/', views.FTApple, name='FTApple'),
    path('LoginRegister/FTAndroid/', views.FTAndroid, name='FTAndroid'),
    path('LoginRegister/FTSponRateTbl/', views.FTSponRateTbl, name='FTSponRateTbl'),
    # path('LoginRegister/FTTransactions/<int:batch_id>', views.FTTransactions, name='FTTransactions'),
    # path('LoginRegister/FTTransactions/', views.FTTransactions, name='FTTransactionsNoId'),
    # path('transactions/delete/<int:pk>/', views.transaction_delete, name='transaction_delete'),
    path('admin/', admin.site.urls),
    path('logout_user/', views.logout_user, name='logout'),
    path('LoginRegister/mainlandingpage/', views.mainlandingpage, name='mainlandingpage')
]

cal/urls.py
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.event, name='event_new'),
    path('event/edit/<int:event_id>/', views.event, name='event_edit'),
]

familytracks/urls.py
from django.urls import path
from . import views

app_name = 'familytracks'

urlpatterns = [
    path('', views.home, name="home"),
    path('main_landing_page/', views.main_landing_page, name='main_landing_page'),
    path('profiles_list/', views.profiles_list, name='profiles_list'),
    path('profile/<int:pk>', views.profile, name='profile'),
    path('profile/followers/<int:pk>', views.followers, name='followers'),
    path('profile/follows/<int:pk>', views.follows, name='follows'),
    path('meep_like/<int:pk>', views.meep_like, name='meep_like'),
    path('meep_show/<int:pk>', views.meep_show, name='meep_show'),
    path('unfollow/<int:pk>', views.unfollow, name='unfollow'),
    path('follow/<int:pk>', views.follow, name='follow'),
    path('delete_meep/<int:pk>', views.delete_meep, name="delete_meep"),
    path('edit_meep/<int:pk>', views.edit_meep, name="edit_meep"),
    path('search/', views.search, name='search'),
    path('search_user/', views.search_user, name='search_user'),
    # path('play_video/', views.play_video, name='play_video'),

]

fitness/urls.py
from django.urls import path
from . import views

app_name = 'fitness'

urlpatterns = [
    path('', views.home, name="home"),
    path('main_landing_page/', views.main_landing_page, name='main_landing_page'),
    path('', views.tutorial, name="tutorial"),
    path('app_tutorial/', views.tutorial, name='tutorial2'),
    path('upperbodygymworkouts/', views.UpperBodyGymWorkouts, name='UpperBodyGymWorkouts'),
    path('upperbodyhomeworkouts/', views.UpperBodyHomeWorkouts, name='UpperBodyHomeWorkouts'),
    path('training_routines', views.training_routines, name='training_routines'),
    path('search_workouts', views.search_workouts, name='search_workouts' ),
    path('show_workout/<int:workout_id>', views.show_workout, name='show_workout'),
    path('show_excercise/<int:excercise_id>', views.show_excercise, name='show_excercise'),
    path('exercise_update/<int:pk>', views.exercise_update, name='exercise_update'),
    path('exercise_delete/<int:pk>', views.exercise_delete, name='exercise_delete'),
    path('show_routine/<int:routine_id>', views.show_routine, name='show_routine'),
    path('show_construction', views.show_construction, name='show_construction'),
    path('workouts', views.workouts, name='workouts'),
    path('excercises', views.excercises, name='excercises'),
    path('addworkout', views.AddWorkout, name='AddWorkout'),
    path('addexcercise', views.AddExcercise, name='AddExcercise'),
    path('addroutine', views.AddRoutine, name='AddRoutine'),
    path('addgolfcourse', views.AddGolfCourse, name='AddGolfCourse'),    
    path('golfscore', views.AddGolfScore, name='AddGolfScore'),    
    path('golf_courses', views.golf_courses, name='golf_courses'),
    path('show_golf_course/<int:golf_course_id>', views.show_golf_course, name='show_golf_course'),
    path('golf_rounds', views.golf_rounds, name='golf_rounds'),
    path('show_golf_round/<int:golf_round_id>', views.show_golf_round, name='show_golf_round'),
    ]                                      

listsplan/urls.py
from django.urls import path
from . import views

app_name = 'listsplan'

urlpatterns = [
    path('', views.home, name="home"),
    path('main_landing_page/', views.main_landing_page, name='main_landing_page'),
    path('FTListChores/', views.FTListChores, name='FTListChores'),
    path('FTListChores/<int:listheader_id>/', views.FTListChores, name='FTListChores_with_id'),
    path('listHeader/delete/<int:pk>/', views.listHeader_delete, name='listHeader_delete'),
    path('listDetail/delete/<int:pk>/', views.listDetail_delete, name='listDetail_delete'),
    path('listHeader_update/update/<int:pk>/', views.listHeader_update, name='listHeader_update'),
    path('listDetail_update/update/<int:pk>/', views.listDetail_update, name='listDetail_update'),
]

transactions/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'transactions'

urlpatterns = [
    path('', views.home, name="home"),
    path('main_landing_page/', views.main_landing_page, name='main_landing_page'),
    path('income_accts', views.income_accts, name='income_accts'),
    path('cashinacctm/update/<int:pk>/', views.cashinacctm_update, name='cashinacctm_update'),
    path('cashinacctm/delete/<int:pk>/', views.cashinacctm_delete, name='cashinacctm_delete'),
    path('show_construction', views.show_construction, name='show_construction'),
    path('accounts', views.accounts, name='accounts'),
    path('show_account/<int:account_id>', views.show_account, name='show_account'),
    path('search_accounts', views.search_accounts, name='search_accounts' ),
    path('statement-sectionsV/', views.StatementSectionsV, name='statement_section'),
    path('statement-sectionsV/<int:pk>/', views.StatementSectionsV, name='statement_section_with_id'),
    path('statement-sectionsV/delete/<int:pk>/', views.StatementSections_deleteV, name='section_delete'),
    path('statement-sectionsV/update/<int:pk>/', views.StatementSections_updateV, name="section_update"), # type: ignore
    path('statement/delete/<int:pk>/', views.Statement_deleteV, name='statement_delete'), # type: ignore
    path('statement/update/<int:pk>/', views.statement_update, name='statement_update'), # type: ignore
    path('statement-sectionsV/line/delete/<int:pk>/', views.SectionLines_deleteV, name='line_delete'),
    path('statement-sectionsV/line/update/<int:pk>/', views.SectionLines_updateV, name='line_update'),
    path('statement-sectionsV/account/delete/<int:pk>/', views.LineAccounts_deleteV, name='account_delete'),
    path('statement-sectionsV/account/update/<int:pk>/', views.LineAccounts_updateV, name='account_update'),
    path('statement-linesline/<int:listheader_id>/', views.SectionLinesV, name='statement_linesline'),
    path('statement-line-accountsV/delete/<int:pk>/', views.LineAccountsV, name='StatementLinesDetails_delete'),
    path('cash-flow-statement/', views.cash_flow_statement_view, name='cash_flow_statement'),
]

LoginRegister/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import AuthenticationForm
from .models import SponRates


INPUT_CLASSES = 'rounded-xl border form-control'

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SponRatesForm(forms.ModelForm):  
    class Meta:
        model = SponRates
        fields = ('Sequence', 'Geography', 'Population', 'FTUserCount', 'Spots1_6Rate', 'Spot7Rate')
        widgets = {
            'Sequence': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'Geography': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'Population': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'FTUserCount': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'Spots1_6Rate': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'Spot7Rate': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            })
        }

# 
#   KMS Start Day Picker
# 
class DateInput(forms.DateInput):
    input_type = 'date'

class UploadExcelForm(forms.Form):
    excel_file = forms.FileField()

class TemplateActionForm(forms.Form):
    ACTION_CHOICES = [
        ('', 'Choose an action...'),
        ('download', 'Download Template'),
        ('upload', 'Upload Template'),
    ]

    action = forms.ChoiceField(choices=ACTION_CHOICES, required=True)
    excel_file = forms.FileField(required=False)

LoginRegister/templates/FTDefAcctsMenu.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Finances Menu{% endblock %}

{% block pageimage %}
<img style="float: left;" src="{% static 'Finances.jpg' %}" alt="Main Menu Tile missing" width="100"
  height="100">
{% endblock %}
{% block backurl %}{%url 'LoginRegister:FTMainMenu'%}{% endblock %}

{% block pageTitle %}
<div class="h1">
  <a style="color:rgb(6, 6, 192)">
    <p style="font-size:40px">
      <h2>Finances Menu</h2>
    </p>
  </a>
</div>
{% endblock %}

{% block content %}
<br>
<br>
<p style="text-align:center">
  <a href="{% url 'LoginRegister:FTRevenueAccts' %}"><img src="{% static 'CashIn.jpg' %}" alt="Cash In Tile Missing" width="130" height="130"></a>
  <a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp </a>
  <a href="{% url 'LoginRegister:FTExpAccts' %}"><img src="{% static 'CashOut.jpg' %}" alt="Cash Out Tile Missing" width="130" height="130"></a>
  <a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp </a>
  <a href="{% url 'LoginRegister:FTAssetAccts' %}"><img src="{% static 'WhatWeOwn.jpg' %}" alt="What We OwnTile Missing" width="130" height="130"></a>
  <a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp </a>
  <a href="{% url 'LoginRegister:FTLiabAccts' %}"><img src="{% static 'WhatWeOwe.jpg' %}" alt="To Do's Tile Missing" width="130" height="130"></a>
  <a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp </a>
  <a href="{% url 'LoginRegister:FTEquityAccts' %}"><img src="{% static 'Networth.jpg' %}" alt="To Do's Tile Missing" width="130" height="130"></a>
</p>
      
<p style="text-align:center">
  <a href="{% url 'LoginRegister:FTAcctGroupings' %}"><img src="{% static 'AccountGrouping.jpg' %}" alt="Accont Groupings  Tile Missing" width="130" height="130"></a>
  <a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp </a>
  <a href="{% url 'LoginRegister:FTGroupingDrillDown' %}"><img src="{% static 'GroupingDrillDown.jpg' %}" alt="Grouping Drill-Down Tile Missing" width="130" height="130"></a>
  <a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp </a>
  <a href="{% url 'LoginRegister:FTAccountDrillDown' %}"><img src="{% static 'AccountDrillDown.jpg' %}" alt="Account Drill-Down Tile Missing" width="130" height="130"></a>
{% endblock %}





















{% load static %}
<!DOCTYPE html>
<html>
  <style>
    div.h1 {text-align: center
    }
  </style>
<body style="background-color:#DDEBF7;">

<p>
<img style="float: left;" src="{% static 'DefineAccountsMenu.jpg' %}" alt="Define Accounts Menu Tile missing" width="100" height="100">
<img style="float: right;" src="{% static 'HeaderRight.jpg' %}" alt="Login Tile" width="100" height="100">

<p style="font-size:12px" >
    &nbsp&nbsp&nbsp&nbsp<a href="FTAcministration/" style="color:blue">Support</a>&nbsp&nbsp
    <a href="FTAcministration/" style="color:blue">Suggestions</a>&nbsp&nbsp
    <a href="FTAcministration/" style="color:blue">Service Requests</a>&nbsp&nbsp
    <a href="FTAcministration/" style="color:blue">Contact Us</a>&nbsp&nbsp
    <a href="FTAcministration/" style="color:blue">About</a>&nbsp&nbsp
    <a href="FTAcministration/" style="color:blue">Help</a>&nbsp&nbsp
    <a href="{% url 'LoginRegister:FTFinMenu' %}"style="color:blue">Back</a></p>
    <p>     
  </p>
</a>
<div class="h1">
  <a style="color:rgb(6, 6, 192)">
    <p style="font-size:40px"
      <h2>Account Maintenance Menu</h2>
    </p>
  </a>
</div> 
</p>
<br>

<p style="text-align:center">
    <a href="{% url 'LoginRegister:FTRevenueAccts' %}"><img src="{% static 'CashIn.jpg' %}" alt="Cash In Tile Missing" width="130" height="130"></a>
    <a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp </a>
    <a href="{% url 'LoginRegister:FTExpAccts' %}"><img src="{% static 'CashOut.jpg' %}" alt="Cash Out Tile Missing" width="130" height="130"></a>
    <a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp </a>
    <a href="{% url 'LoginRegister:FTAssetAccts' %}"><img src="{% static 'WhatWeOwn.jpg' %}" alt="What We OwnTile Missing" width="130" height="130"></a>
    <a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp </a>
    <a href="{% url 'LoginRegister:FTLiabAccts' %}"><img src="{% static 'WhatWeOwe.jpg' %}" alt="To Do's Tile Missing" width="130" height="130"></a>
    <a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp </a>
    <a href="{% url 'LoginRegister:FTEquityAccts' %}"><img src="{% static 'Networth.jpg' %}" alt="To Do's Tile Missing" width="130" height="130"></a>
  </p>
        
<p style="text-align:center">
    <a href="{% url 'LoginRegister:FTAcctGroupings' %}"><img src="{% static 'AccountGrouping.jpg' %}" alt="Accont Groupings  Tile Missing" width="130" height="130"></a>
    <a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp </a>
    <a href="{% url 'LoginRegister:FTGroupingDrillDown' %}"><img src="{% static 'GroupingDrillDown.jpg' %}" alt="Grouping Drill-Down Tile Missing" width="130" height="130"></a>
    <a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp </a>
    <a href="{% url 'LoginRegister:FTAccountDrillDown' %}"><img src="{% static 'AccountDrillDown.jpg' %}" alt="Account Drill-Down Tile Missing" width="130" height="130"></a>
</p>

<br>
<img align="bottom" src="{% static 'sponsor2.jpg' %}" alt="Sponsor" width="1170" height="125">
      
</body>
</html>

LoginRegister/templates/FTMainMenu.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Main Menu{% endblock %}

{% block content %}
<div class="h1">
  <a style="color:rgb(6, 6, 192)">
    <p style="font-size:40px">
      <h2>Main Menu</h2>
    </p>
  </a>
</div>
<br>
<p style="text-align:center">
  <a href="{% url 'transactions:main_landing_page' %}"><img src="{% static 'Finances.jpg' %}" alt="Finances Splash Missing" width="130" height="130"></a>
  <a> &nbsp</a>
  <a href="{% url 'calendar10:main_landing_page' %}"><img src="{% static 'calendar.jpg' %}" alt="Calendar Splash Missing" width="130" height="130"></a>
  <a> &nbsp</a>
  <a href="{% url 'listsplan:main_landing_page' %}"><img src="{% static 'ListsAndPlanning.jpg' %}" alt="Lists & Planning Splash Missing" width="130" height="130"></a>
  <a> &nbsp</a>
  <a href="{% url 'familytracks:main_landing_page' %}"><img src="{% static 'FamilyTracks.jpg' %}" alt="Family Tracks Splash Missing" width="130" height="130"></a>
  <a> &nbsp</a>
  <a href="{% url 'fitness:main_landing_page' %}"><img src="{% static 'FitnessSports.jpg' %}" alt="Fitness Sports Splash Missing" width="130" height="130"></a>
  <a> &nbsp</a>
  <a href="{% url 'administration:main_landing_page' %}"><img src="{% static 'Administration.jpg' %}" alt="Admin Splash Missing" width="130" height="130"></a>
</p>
      

<p style="text-align:center">
  <!-- <a href="{% url 'LoginRegister:FTFitnessSports' %}"><img src="{% static 'FitnessSports.jpg' %}" alt="Fitness Sports Tile Missing" width="130" height="130"></a> -->
</p>

{% endblock %}

LoginRegister/templates/edit.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <script src="https://cdn.tailwindcss.com"></script>
  <!-- Add this code to your Django template -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

</head>

<body style="background-color:#DDEBF7;">
  <!-- KMS Start -->
  <div class="container" style="max-width: 100%;">
    <div class="row">
      <div class="col-md-12">
        <p>
          <img style="float: left;" src="{% static 'Finances.jpg' %}" alt="Finances Tile missing" width="100"
            height="100">
        <p style="font-size:12px">
          &nbsp&nbsp&nbsp&nbsp<a href="FTAcministration/" style="color:blue">Support</a>&nbsp&nbsp
          <a href="FTAcministration/" style="color:blue">Suggestions</a>&nbsp&nbsp
          <a href="FTAcministration/" style="color:blue">Service Requests</a>&nbsp&nbsp
          <a href="FTAcministration/" style="color:blue">Contact Us</a>&nbsp&nbsp
          <a href="FTAcministration/" style="color:blue">About</a>&nbsp&nbsp
          <a href="FTAcministration/" style="color:blue">Help</a>&nbsp&nbsp
          <img style="float: right;" src="{% static 'HeaderRight.jpg' %}" alt="Login Tile" width="100" height="100">
        </p>
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        </a>
        <img class="family" src="{% static 'FamilyName.jpg' %}" alt="Family Name" width="400" height="150">
        </p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <p>
        <h2>Capture Family Transactions</h2>
        <a href="{% url 'LoginRegister:LoginRegister' %}" style="color:blue">Capture Transactions</a><br>
        <a href="{% url 'LoginRegister:LoginRegister' %}" style="color:blue">Monthly Close</a><br>
        </p>

        <p>
        <h2>Family Financial Reports</h2>
        <a href="{% url 'LoginRegister:LoginRegister' %}" style="color:blue">Family Earnings</a><br>
        <a href="{% url 'LoginRegister:LoginRegister' %}" style="color:blue">Family Networth</a><br>
        <a href="{% url 'LoginRegister:LoginRegister' %}" style="color:blue">Cash Flow</a><br>
        </p>

        <p>
        <h2>Family Accounts</h2>
        <a href="{% url 'LoginRegister:LoginRegister' %}" style="color:blue">Cash In</a><br>
        <a href="{% url 'LoginRegister:LoginRegister' %}" style="color:blue">Cash Out</a><br>
        <a href="{% url 'LoginRegister:LoginRegister' %}" style="color:blue">What We Own</a><br>
        <a href="{% url 'LoginRegister:LoginRegister' %}" style="color:blue">Debts</a><br>
        <a href="{% url 'LoginRegister:LoginRegister' %}" style="color:blue">Networth</a><br>
        <a href="{% url 'LoginRegister:LoginRegister' %}" style="color:blue">Grouping Drill Down</a><br>
        <a href="{% url 'LoginRegister:LoginRegister' %}" style="color:blue">Account Drill Down</a><br>
      </div>
      <div class="col-md-4">
        <!--  -->
        <!-- Cash In -->
        <!--  -->
        <h2>{{ title }}</h2>
        <form id="editForm" action="{% url 'LoginRegister:cashinacctm_update' cashinacctm.id %}" method="post">
          {% csrf_token %}
          <div class="form-group">
            <label for="{{ form.AccountNumber.id_for_label }}">Account Number</label>
            {{ form.AccountNumber }}
          </div>
          <div class="form-group">
            <label for="{{ form.Description.id_for_label }}">Description</label>
            {{ form.Description }}
          </div>
          {% if form.errors or form.non_field_errors %}
          <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
          </div>
          {% endif %}
          <button type="submit"
            class="mt-6 mb-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
      </div>
      <!-- Add modal -->
      <div class="col-md-4">
      </div>
      <!-- Edit modal -->

    </div>

    <br>
    </p>
    <p>Back to <a href="{% url 'LoginRegister:FTMainMenu' %}">Main Menu</a></p>
    <br>
    <img class="sponsor" src="{% static 'sponsor.jpg' %}" alt="Sponsor" width="1170" height="125">
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
    crossorigin="anonymous"></script>
  <!-- <script src="{% static 'js/child.js' %}"></script> -->
</body>

</html>