FamilyTrackerAuth/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('LoginRegister.urls')),
    path('admin/', admin.site.urls),
    path('events/', include('events.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path('fitness/', include('fitness.urls')),
    path('calendar/', include('calendar10.urls')),
    path('transactions/', include('transactions.urls')),
    path('familytracks/', include('familytracks.urls')),
    path('cal/', include('cal.urls')),
    path('administration/', include('administration.urls')),
    path('listsplan/', include('listsplan.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cal/urls.py
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.event, name='event_new'),
    path('event/edit/<int:event_id>/', views.event, name='event_edit'),
]

fitness/urls.py
from django.urls import path
from . import views

app_name = 'fitness'

urlpatterns = [
    path('', views.home, name="home"),
    path('main_landing_page/', views.main_landing_page, name='main_landing_page'),
    path('', views.tutorial, name="tutorial"),
    path('app_tutorial/', views.tutorial, name='tutorial2'),
    path('upperbodygymworkouts/', views.UpperBodyGymWorkouts, name='UpperBodyGymWorkouts'),
    path('upperbodyhomeworkouts/', views.UpperBodyHomeWorkouts, name='UpperBodyHomeWorkouts'),
    path('training_routines', views.training_routines, name='training_routines'),
    path('search_workouts', views.search_workouts, name='search_workouts' ),
    path('show_workout/<int:workout_id>', views.show_workout, name='show_workout'),
    path('show_excercise/<int:excercise_id>', views.show_excercise, name='show_excercise'),
    path('exercise_update/<int:pk>', views.exercise_update, name='exercise_update'),
    path('exercise_delete/<int:pk>', views.exercise_delete, name='exercise_delete'),
    path('show_routine/<int:routine_id>', views.show_routine, name='show_routine'),
    path('show_construction', views.show_construction, name='show_construction'),
    path('workouts', views.workouts, name='workouts'),
    path('excercises', views.excercises, name='excercises'),
    path('addworkout', views.AddWorkout, name='AddWorkout'),
    path('addexcercise', views.AddExcercise, name='AddExcercise'),
    path('addroutine', views.AddRoutine, name='AddRoutine'),
    path('addgolfcourse', views.AddGolfCourse, name='AddGolfCourse'),    
    path('golfscore', views.AddGolfScore, name='AddGolfScore'),    
    path('golf_courses', views.golf_courses, name='golf_courses'),
    path('show_golf_course/<int:golf_course_id>', views.show_golf_course, name='show_golf_course'),
    path('golf_rounds', views.golf_rounds, name='golf_rounds'),
    path('show_golf_round/<int:golf_round_id>', views.show_golf_round, name='show_golf_round'),
    ]                                      

listsplan/forms.py
from django import forms

from .models import ListHeaderT, ListDetailsT

INPUT_CLASSES = 'rounded-xl border form-control'

class ListHeaderTForm(forms.ModelForm):
    class Meta:
        model = ListHeaderT
        fields = ('LHName', 'LHDescription',)
        widgets = {
            'LHName': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'LHDescription': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            })
        }

class ListDetailsTForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        list_header = kwargs.pop('list_header', None)  # Get the passed list_header and remove from kwargs
        super(ListDetailsTForm, self).__init__(*args, **kwargs)
        if list_header:
            self.fields['ListHeaderFK'].initial = list_header

            self.fields['ListDetailFK'].queryset = ListDetailsT.objects.filter(ListHeaderFK=list_header)

    class Meta:
        model = ListDetailsT
        fields = ('ListHeaderFK', 'ListDetailFK', 'LNNumber', 'LHName')
        widgets = {
            'ListHeaderFK': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'ListDetailFK': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'LNNumber': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'LHName': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
        }
    ListHeaderFK = forms.ModelChoiceField(queryset=ListHeaderT.objects.all(), widget=forms.Select(attrs={'class': INPUT_CLASSES}))
    ListDetailFK = forms.ModelChoiceField(queryset=ListDetailsT.objects.all(), widget=forms.Select(attrs={'class': INPUT_CLASSES}), required=False)

class ListHeaderSelectForm(forms.ModelForm):
    class Meta:
        model = ListHeaderT
        fields = ['LHName']

    LHName = forms.ModelChoiceField(queryset=ListHeaderT.objects.all(), widget=forms.Select(attrs={'class': INPUT_CLASSES}))

fitness/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.urls import reverse
import csv
import io
from .models import workout, training_routine, ExcerciseList, golf_course
from .models import *
from .forms import WorkoutForm
from .forms import ExcerciseForm
from .forms import RoutineForm
from .forms import GolfCourseForm
from .forms import GolfScoreForm
from django.views import generic
from django.core.paginator import Paginator
from django.http import JsonResponse
from LoginRegister.utils import increment_click_count

def home(request):
    return render(request, 'fitness/main_landing_page.html', {})

def main_landing_page(request):
    click_count = increment_click_count('fitness')
    return render(request, 'fitness/main_landing_page.html', {'click_count': click_count,})

def tutorial(request):
    return render(request, 'fitness/app_tutorial.html', {})

def UpperBodyGymWorkouts(request):
    return render(request, 'fitness/UpperBodyGymWorkouts.html', {})

def UpperBodyHomeWorkouts(request):
    return render(request, 'fitness/UpperBodyHomeWorkouts.html', {})

def AddWorkout(request):
    submitted = False
    if request.method == "POST":
        form = WorkoutForm(request.POST)
        if form.is_valid():
            form.save() 
            return HttpResponseRedirect('addworkout?submitted=True')   
    else:
        form = WorkoutForm
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'fitness/AddWorkout.html', {'form':form, 'submitted':submitted})

def AddExcercise(request):
    submitted = False
    if request.method == "POST":
        form = ExcerciseForm(request.POST)
        if form.is_valid():
            form.save() 
            return HttpResponseRedirect('addexcercise?submitted=True')   
    else:
        form = ExcerciseForm
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'fitness/AddExcercise.html', {'form':form, 'submitted':submitted})

def AddRoutine(request):
    submitted = False
    if request.method == "POST":
        form = RoutineForm(request.POST)
        if form.is_valid():
            form.save() 
            return HttpResponseRedirect('addroutine?submitted=True')   
    else:
        form = RoutineForm
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'fitness/AddRoutine.html', {'form':form, 'submitted':submitted})

def AddGolfCourse(request):
    yardage_fields = [f'Hole{i}Yardage' for i in range(1, 19)]
    handicap_fields = [f'Hole{i}Handicap' for i in range(1, 19)]
    submitted = False
    if request.method == "POST":
        form = GolfCourseForm(request.POST)
        if form.is_valid():
            form.save() 
            return HttpResponseRedirect('addgolfcourse?submitted=True')   
    else:
        form = GolfCourseForm
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'fitness/AddGolfCourse.html', {'form':form, 'submitted':submitted,  'yardage_fields': yardage_fields,
        'handicap_fields': handicap_fields,})

def training_routines(request):
    routine_list = training_routine.objects.all()

    # Set up Pagination
    p = Paginator(training_routine.objects.all(), 8)
    page = request.GET.get('page')
    routine_p = p.get_page(page)
    nums = "x" * routine_p.paginator.num_pages
    return render(request, 'fitness/training_routines.html', {
        'routine_list': routine_list,
        'routine_p': routine_p,
        'nums' :nums
        })

def search_workouts(request):
    if request.method == "POST":
        searched = request.POST['searched']   
        workouts = workout.objects.filter(WorkoutName__contains=searched)
        return render(request, 'fitness/search_workouts.html', {'searched':searched, 'workouts':workouts})
    else:
        return render(request, 'fitness/search_workouts.html', {})


def workouts(request):
    workout_list = workout.objects.all()
    return render(request, 'fitness/workouts.html', {'workout_list': workout_list})

def show_workout(request, workout_id):
    workout_info = workout.objects.get(pk=workout_id)
    return render(request, 'fitness/show_workout.html', {'workout': workout_info})

def show_excercise(request, excercise_id):
    excercise_info = ExcerciseList.objects.get(pk=excercise_id)
    return render(request, 'fitness/show_excercise.html', {'excercise': excercise_info})

def show_golf_course(request, golf_course_id):
    course_info = golf_course.objects.get(pk=golf_course_id)

    # Extract relevant data from the course_info
    data = {
        'Hole1Par': course_info.Hole1Par,
        'Hole2Par': course_info.Hole2Par,
        'Hole3Par': course_info.Hole3Par,
        'Hole4Par': course_info.Hole4Par,
        'Hole5Par': course_info.Hole5Par,
        'Hole6Par': course_info.Hole6Par,
        'Hole7Par': course_info.Hole7Par,
        'Hole8Par': course_info.Hole8Par,
        'Hole9Par': course_info.Hole9Par,
        'Hole10Par': course_info.Hole10Par,
        'Hole11Par': course_info.Hole11Par,
        'Hole12Par': course_info.Hole12Par,
        'Hole13Par': course_info.Hole13Par,
        'Hole14Par': course_info.Hole14Par,
        'Hole15Par': course_info.Hole15Par,
        'Hole16Par': course_info.Hole16Par,
        'Hole17Par': course_info.Hole17Par,
        'Hole18Par': course_info.Hole18Par,
        # Add other fields here
    }

    # If it's an AJAX request, return JSON
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return JsonResponse(data)
    return render(request, 'fitness/show_golf_course.html', {'golf_course': course_info})

def show_golf_round(request, golf_round_id):
    round_info = golf_score.objects.get(pk=golf_round_id)

    # Extract relevant data from the course_info
    data = {
        'Hole1Par': round_info.Hole1Par,
        'Hole2Par': round_info.Hole2Par,
        'Hole3Par': round_info.Hole3Par,
        'Hole4Par': round_info.Hole4Par,
        'Hole5Par': round_info.Hole5Par,
        'Hole6Par': round_info.Hole6Par,
        'Hole7Par': round_info.Hole7Par,
        'Hole8Par': round_info.Hole8Par,
        'Hole9Par': round_info.Hole9Par,
        'Hole10Par': round_info.Hole10Par,
        'Hole11Par': round_info.Hole11Par,
        'Hole12Par': round_info.Hole12Par,
        'Hole13Par': round_info.Hole13Par,
        'Hole14Par': round_info.Hole14Par,
        'Hole15Par': round_info.Hole15Par,
        'Hole16Par': round_info.Hole16Par,
        'Hole17Par': round_info.Hole17Par,
        'Hole18Par': round_info.Hole18Par,
        # Add other fields here
    }

    # If it's an AJAX request, return JSON
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return JsonResponse(data)
    return render(request, 'fitness/show_golf_round.html', {'round_info': round_info})

def show_routine(request, routine_id):
    routine_info = training_routine.objects.get(pk=routine_id)
    return render(request, 'fitness/show_routine.html', {'routine': routine_info})

def show_construction(request):
    return render(request, 'fitness/show_construction.html', {})

def excercises(request):
    excercise_list = ExcerciseList.objects.all()

    # Set up Pagination
    p = Paginator(ExcerciseList.objects.all(), 11)
    page = request.GET.get('page')
    excer_p = p.get_page(page)
    nums = "x" * excer_p.paginator.num_pages

    if request.method == 'POST':
        form = ExcerciseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('fitness:excercises')
    else:
        exerciseForm = ExcerciseForm()
        # print(exerciseForm)

    return render(request, 'fitness/excercises.html', {
        'exerciseForm': exerciseForm,
        'excercise_list': excercise_list,
        'excer_p':excer_p,
        'nums':nums
        })

def exercise_update(request, pk):
    exercice = get_object_or_404(ExcerciseList, pk=pk)
    if request.method == 'POST':
        form = ExcerciseForm(request.POST, instance=exercice)
        if form.is_valid():
            form.save()
            return redirect('fitness:excercises')
    else:
        form = ExcerciseForm(instance=exercice)
    return render(request, 'fitness/excercises.html', {
        'form': form,
        'exercice': exercice,
        'title': 'Edit Cash In Account',
    })

def golf_courses(request):
    course_list = golf_course.objects.all()

    # Set up Pagination
    p = Paginator(golf_course.objects.all(), 8)
    page = request.GET.get('page')
    course_p = p.get_page(page)
    nums = "x" * course_p.paginator.num_pages
    return render(request, 'fitness/golf_courses.html', {
        'course_list':course_list,
        'course_p':course_p,
        'nums':nums
        })
 
def AddGolfScore(request):
    score_fields = [f'Hole{i}Score' for i in range(1, 19)]
    submitted = False
    if request.method == "POST":
        form = GolfScoreForm(request.POST)
        if form.is_valid():
            form.save() 
            return HttpResponseRedirect('addgolfscore?submitted=True')   
    else:
        form = GolfScoreForm
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'fitness/golf_score.html', {'form':form, 'submitted':submitted, 'score_fields': score_fields})

def golf_rounds(request):
    round_list = golf_score.objects.all()

    # Set up Pagination
    p = Paginator(golf_score.objects.all(), 8)
    page = request.GET.get('page')
    round_p = p.get_page(page)
    nums = "x" * round_p.paginator.num_pages
    return render(request, 'fitness/golf_rounds.html', {
        'round_list':round_list,
        'round_p':round_p,
        'nums':nums
        })

fitness/templates/fitness/AddExcercise.html
{% extends 'fitness/baseex.html' %}
{% load static %}
{% block content %}
<p style="text-align:center">
  <div class="h1">
    <a style="color:rgb(6, 6, 192)">
      <p style="font-size:40px">
        <h2>Add Excercise</h2>
      </p>
    </a>
  </div>
</p>
{% if submitted %}
    Excercise Added Successfully

{% else %}

    <form action="" method=POST>
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="Add Excercise" class="btn btn-secondary">

    </form>

{% endif %}

{% endblock %}

fitness/templates/fitness/CoreGymWorkouts.html
{% extends 'fitness/base.html' %}
{% load static %}

{% block pageTitle %}
{% endblock %}
{% block content %}
<p style="text-align:center">
  <div class="h1">
    <a style="color:rgb(6, 6, 192)">
      <p style="font-size:40px">
        <h2>Core Gym Workouts</h2>
      </p>
    </a>
  </div>
</p>
{% endblock %}

fitness/templates/fitness/CoreHomeWorkouts.html
{% extends 'fitness/base.html' %}
{% load static %}

{% block pageTitle %}
{% endblock %}
{% block content %}
<p style="text-align:center">
  <div class="h1">
    <a style="color:rgb(6, 6, 192)">
      <p style="font-size:40px">
        <h2>Core Home Workouts</h2>
      </p>
    </a>
  </div>
</p>
{% endblock %}

fitness/templates/fitness/UpperBodyHomeWorkouts.html
{% extends 'fitness/base.html' %}
{% load static %}

{% block pageTitle %}
{% endblock %}
{% block content %}
<p style="text-align:center">
  <div class="h1">
    <a style="color:rgb(6, 6, 192)">
      <p style="font-size:40px">
        <h2>Upper Body Home Workouts</h2>
      </p>
    </a>
  </div>
</p>
{% endblock %}

fitness/templates/fitness/golf_rounds.html
{% extends 'fitness/base_golf.html' %}
{% load static %}

{% block pageTitle %}
{% endblock %}
{% block content %}
<p style="text-align:center">
  <div class="h1">
    <a style="color:rgb(6, 6, 192)">
      <p style="font-size:40px">
        <h2>Golf Rounds</h2>
      </p>
    </a>
  </div>
</p>
<br/>
<center>
  <table style="width:100%" class="table table-bordered table-striped table-hover">
    <th class="table-primary"><h4>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp All Golf Rounds</h4></th>
    {% for golf_round in round_p %}
      <tr class="table-secondary table-active">
        <td ><a href="{% url 'fitness:show_golf_round' golf_round.id %}">{{ golf_round.Date }}&nbsp&nbsp&nbsp&nbsp({{ golf_round.Score }})&nbsp&nbsp{{ golf_round.GolfCourse }}</a></td>
      </tr>
    {% endfor %}
  </table> 
</center>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
  
  {% if golf_rounds_p.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ golf_rounds_p.previous_page_number }}">Previous</a></li>
  {% endif %}
  
  {% for i in nums %}
      <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
  {% endfor %}
  
  {% if golf_rounds_p.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ golf_rounds_p.next_page_number }}">Next</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ golf_rounds_p.paginator.num_pages }}">Last &raquo</a></li>
  {% endif %}
  
  </ul>
  </nav>
  

{% endblock %}

fitness/templates/fitness/main_landing_page.html
{% extends 'fitness/base_no_search.html' %}
{% load static %}

{% block pageTitle %}
{% endblock %}
{% block content %}
<p style="text-align:center">
  <div class="h1">
    <a style="color:rgb(6, 6, 192)">
      <p style="font-size:40px">
        <h2>Fitness and Sports</h2>
        <h6>Members: 86 | Clicks: {{ click_count }}</h6>
      </p>
    </a>
  </div>
</p>
</br>
<p style="text-align:center">
  <div class="col-md-12" style="text-align: center;">
    <div style="width: 100%; height: 400px;">
      <img src="{% static 'Gym.jpg' %}" style="height: 95%;" alt="Generic Gym">
    </div>
  </div>
</p>
{% endblock %}

fitness/templates/fitness/show_excercise.html
{% extends 'fitness/baseex.html' %}
{% load static %}

{% block content %}
<p style="text-align:center">
  <div class="h1">
    <a style="color:rgb(6, 6, 192)">
      <p style="font-size:40px">
        <h2>Excercise</h2>
      </p>
    </a>
  </div>
</p>
<html lang="en">
<head>
  <title>Bootstrap Card</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
</head>

<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header bg-secondary text-white">
                <strong>{{ excercise.Reference }}:&nbsp&nbsp{{ excercise.Region }}&nbsp&nbsp{{ excercise.Exercise }}</strong>
            </div>
            <div class="card-body card bg-light text-dark">
                <p class="card text-left" style="padding: 0 15px 15px;"><br>
                    <strong>Description:</strong>{{ excercise.Description }}</br></br>
                    <strong>Instructions:</strong>{{ excercise.Instructions }}
                </p>
            </div>
        </div>
    </div>
</div>

{% block modal-script %}
<script>
  $(document).ready(function () {

    $('#editExcerciseButton').click(function (e) {
      e.preventDefault();

      let id = $(this).data('id');
      let reference = $(this).data('Reference');
      let region = $(this).data('Region');
      let excercise = $(this).data('Exercise');
      let description = $(this).data('Description');
      let instructions = $(this).data('Instructions');

      // Fill the form with data
      // $("#id_ListHeaderFK option").each(function () {
      //   if ($(this).text() == ListHeaderFK) {
      //     $(this).attr('selected', 'selected');
      //   }
      // });

      $('#excerciseForm input[name="Reference"]').val(reference);
      $('#excerciseForm input[name="Region"]').val(region);
      $('#excerciseForm input[name="Exercise"]').val(excercise);
      $('#excerciseForm input[name="Description"]').val(description);
      $('#excerciseForm input[name="Instructions"]').val(instructions);

      $('#excerciseForm').attr('action', '{% url "fitness:exercise_update" 0 %}'.replace('0', id));
    });

    $('#addExcerciseButton').click(function (e) {
      e.preventDefault();

      // Clear the form fields
      $('#excerciseForm input[name="Reference"]').val('');
      $('#excerciseForm input[name="Region"]').val('');
      $('#excerciseForm input[name="Exercise"]').val('');
      $('#excerciseForm input[name="Description"]').val('');
      $('#excerciseForm input[name="Instructions"]').val('');

      // Reset the form action
      $('#excerciseForm').attr('action', '{% url "fitness:excercises" %}');
    });
  });

</script>
{% endblock %}



{% endblock %}

fitness/templates/fitness/training_routines.html
{% extends 'fitness/baseroutine.html' %}
{% load static %}
{% block pageTitle %}
{% endblock %}
{% block content %}
<p style="text-align:center">
  <div class="h1">
    <a style="color:rgb(6, 6, 192)">
      <p style="font-size:40px">
        <h2>Training Routines</h2>
      </p>
    </a>
  </div>
</p>
<br/>
<center>
<table style="width:50%" class="table table-bordered table-striped table-hover">
    <th class="table-primary">
        <h4>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspAll Routines</h4>
    </th>
    {% for routine in routine_p %}
        <tr class="table-secondary table-active">
            <td><a href="{% url 'fitness:show_routine' routine.id %}">{{ routine.RoutineName }}</a></td>
        </tr>
    {% endfor %}
</table>
</center>
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
  
        {% if excer_p.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ routine_p.previous_page_number }}">Previous</a></li>
        {% endif %}
  
        {% for i in nums %}
             <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
        {% endfor %}
  
        {% if excer_p.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ routine_p.next_page_number }}">Next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ routine_p.paginator.num_pages }}">Last &raquo</a></li>
        {% endif %}
    </ul>
</nav>
{% endblock %}

fitness/templates/fitness/workouts.html
{% extends 'fitness/base.html' %}
{% load static %}
{% block pageTitle %}
{% endblock %}
{% block content %}
<p style="text-align:center">
  <div class="h1">
    <a style="color:rgb(6, 6, 192)">
      <p style="font-size:40px">
        <h2>Workouts</h2>
      </p>
    </a>
  </div>
</p>
<br/>
<center>
  <table style="width:50%" class="table table-bordered table-striped table-hover">
    <th class="table-primary"><h4>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp All Workouts</h4></th>
    {% for workout in workout_list %}
      <tr class="table-secondary table-active">
        <td ><a href="{% url 'fitness:show_workout' workout.id %}">{{ workout.WorkoutName }}</a></td>
      </tr>
    {% endfor %}
  </table>
</center>
{% endblock %}