FamilyTrackerAuth/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('LoginRegister.urls')),
    path('admin/', admin.site.urls),
    path('events/', include('events.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path('fitness/', include('fitness.urls')),
    path('calendar/', include('calendar10.urls')),
    path('transactions/', include('transactions.urls')),
    path('familytracks/', include('familytracks.urls')),
    path('cal/', include('cal.urls')),
    path('administration/', include('administration.urls')),
    path('listsplan/', include('listsplan.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cal/urls.py
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.event, name='event_new'),
    path('event/edit/<int:event_id>/', views.event, name='event_edit'),
]

members/urls.py
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
    path('', views.home, name="home"),
    path('main_menu_login/', views.main_menu_login, name='main_menu_login'),
    path('register_user', views.register_user, name='register_user' ),
    path('update_user', views.update_user, name='update_user' ),
    path('logout_user', views.logout_user, name='logout'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
]

members/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User

# class CustomUser(AbstractUser):
#     password_changed = models.BooleanField(default=False)

# CustomUser._meta.get_field('groups').remote_field.related_name = 'custom_user_groups'
# CustomUser._meta.get_field('user_permissions').remote_field.related_name = 'custom_user_user_permissions'

members/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import AuthenticationForm
# from .models import CashInAcctM, CashOutAcctM, WhatWeOwnAcctM, DebtsAcctM, ListHeaderT, ListDetailsT, NetworthAcctM, SponRates, TransBatch
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

INPUT_CLASSES = 'rounded-xl border form-control'


class RegisterUserForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'form-control'}))
    first_name = forms.CharField(
        max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(
        max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
                  'email', 'password1', 'password2')

    # def __init__(self, *args, **kwargs):
    #     super(RegisterUserForm, self).__init__(*args, **kwargs)

    #     self.fields['username'].widget.attrs['class'] = 'form-control'
    #     self.fields['password1'].widget.attrs['class'] = 'form-control'
    #     self.fields['password2'].widget.attrs['class'] = 'form-control'


    def __init__(self, *args, **kwargs):
        super(RegisterUserForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['username'].label = ''
        self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password1'].label = ''
        self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['password2'].label = ''

class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }), required=True)
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }), required=True)

members/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterUserForm, UpdateUserForm
from django.contrib.auth.models import User
from familytracks.models import Profile
from familytracks.forms import ProfilePicForm
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from .backends import CustomModelBackend


def home(request):
    return render(request, 'members/main_menu_login.html', {})

# def members(request):
    # return render(request, 'members/main_menu_login.html', {})

class ChangePasswordView(PasswordChangeView):
    template_name = 'members/change_password.html'
    success_url = reverse_lazy('LoginRegister:FTMainMenu')

def main_menu_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password, backend=CustomModelBackend)
        if  user is not None:
            login(request, user)
            print(dict(request.session))
            # if not user.password_changed:
            #     user.password_changed = True
            #     user.save()
            if request.session['first_login']:
                if request.session['first_login'] == False:
                    print("this user has logged in before")
                else:
                    print("this is the first login by this user")
                    # Perform actions before last_login is updated
                    request.session['first_login'] = False
                    return redirect('members:change_password')
            # if request.session.get('first_login'):
            #     print("OKKKKKK")
            #     # Clear the session attribute to prevent redirection on subsequent logins
            #     request.session.pop('first_login', None)
            #     return redirect('members:change_password')
            return redirect('LoginRegister:FTMainMenu')
        else:
            messages.success(request, ("There Was An Error Logging In, Please Try Again"))
            return redirect('members:main_menu_login')
    else:
        return render(request, 'members/main_menu_login.html')
    
def logout_user(request):
    logout(request)
    return redirect('members:main_menu_login')

def register_user(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)    
            login(request, user)
            return redirect('LoginRegister:FTMainMenu')
    else:
        form = RegisterUserForm()
    
    return render(request, 'members/register_user.html', {
        'form':form,  
        })

def update_user(request):
    if request.user.is_authenticated:
        current_user = User.objects.get(id=request.user.id)
        profile_user = Profile.objects.get(user__id=request.user.id)
        user_form = UpdateUserForm(request.POST or None, request.FILES or None, instance=current_user)
        profile_form = ProfilePicForm(request.POST or None, request.FILES or None, instance=profile_user)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Your profile has been updated")
            return redirect("familytracks:home")
        return render(request, 'members/update_user.html', {'user_form': user_form, 'profile_form': profile_form})
    else:
        messages.success(request, "You must be logged in to view that page")
        return redirect("members:main_menu_login")

members/templates/members/base.html
<!doctype html>
<html lang="en">
{% load static %}
{% include 'members/modals.html' %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body style="background-color:#DDEBF7;">

    <!-- </head><nav class="navbar navbar-expand-lg navbar-dark bg-dark"> -->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #0f496f;">
        <div class="container-fluid">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" area-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}

            <a class="navbar-brand" href="#">Family Tracker</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'members:register_user' %}">Register</a>
                    </li>

                    <li class="nav-item dropdown active">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Support</a>
                        <ul class="dropdown-menu active" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item active" href="#Supp1" data-bs-toggle="modal">Support</a>
                            </li>
                            <li><a class="dropdown-item active" href="#Sugg1" data-bs-toggle="modal">Suggestions</a>
                            </li>
                            <li><a class="dropdown-item active" href="#Serv1" data-bs-toggle="modal">Service
                                    Requests</a></li>
                        </ul>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" href="#About1" data-bs-toggle="modal">System Tutorial</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="#About1" data-bs-toggle="modal">About</a>
                    </li>

                </ul>
                <ul class="dropdown-menu active" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item active" href="{% url 'events-list' %}">Register Family Members</a>
                    </li>
                    <li><a class="dropdown-item active" href="{% url 'add-event' %}">Assign Security</a></li>
                </ul>
                </li>

                <form class="d-flex" method=POST action="{% url 'search-venues' %}">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" placeholder="Search Venues" aria-label="Search"
                        name="searchedx">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </form>
    </nav>

    <main class="container-fluid mt-4">

        <div class="row" style="margin: 0 5px;">
            <!-- Left Margin Advertising -->
            <div class="col-md-2 order-md-1 order-2" style="text-align: left;">

                <!-- Spot 1 -->
                <div style="background-color: #DDEBF7;" class="d-flex flex-column mb-3">
                    <a href="#exampleModal" data-bs-toggle="modal">
                        <img src="{% static 'AdvSpot1A.jpg' %}" style="height: 95%;" alt="AdvSpot1" class="img-fluid">
                    </a>
                </div>

                <!-- Spot 2 -->
                <div style="background-color: #DDEBF7;" class="d-flex flex-column mb-3">
                    <a href="#ad2Modal" data-bs-toggle="modal">
                        <img src="{% static 'AdvSpot2.jpg' %}" style="height: 95%;" alt="Advpot2" class="img-fluid">
                    </a>
                </div>

                <!-- Spot 3 -->
                <div style="background-color: #DDEBF7;" class="d-flex flex-column mb-3">
                    <a href="#ad3Modal" data-bs-toggle="modal">
                        <img src="{% static 'AdvSpot3.jpg' %}" style="height: 95%;" alt="Advpot2" class="img-fluid">
                    </a>
                </div>

            </div>
            <!-- Center Open Area -->
            <!-- <div class="col-md-8" style="text-align: center;"> -->
            <div class="col-md-8 order-md-2 order-1 mb-2">
                {% block content %}
                {% endblock %}
            </div>

            <!-- Right Margin Advertising -->
            <div class="col-md-2 order-md-3 order-3" style="text-align: right;">

                <!-- Spot 4 -->
                <div style="background-color: #DDEBF7;" class="d-flex flex-column mb-3">
                    <a href="#ad4Modal" data-bs-toggle="modal">
                        <img src="{% static 'AdvSpot4.jpg' %}" style="height: 95%;" alt="Advpot2" class="img-fluid">
                    </a>
                </div>

                <!-- Spot 5 -->
                <div style="background-color: #DDEBF7;" class="d-flex flex-column mb-3">
                    <a href="#ad5Modal" data-bs-toggle="modal">
                        <img src="{% static 'AdvSpot05.jpg' %}" style="height: 95%;" alt="Advpot2" class="img-fluid">
                    </a>
                </div>

                <!-- Spot 6 -->
                <div style="background-color: #DDEBF7;" class="d-flex flex-column mb-3">
                    <a href="#ad6Modal" data-bs-toggle="modal">
                        <img src="{% static 'AdvSpot6.jpg' %}" style="height: 95%;" alt="Advpot2" class="img-fluid">
                    </a>
                </div>

            </div>
        </div>
    </main>

    <footer class="mt-8 text-center">
        <!-- Spot 7 -->
        <div style="background-color: #DDEBF7;">
            <a href="#ad7Modal" data-bs-toggle="modal">
                <img class="sponsor img-fluid" src="{% static 'AdvSpot5B.jpg'%}" style="width: 1450px" alt="Sponsor">
            </a>
        </div>
    </footer>


    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script> -->

</body>

</html>

members/templates/members/change_password.html
<!-- members/change_password.html -->
{% extends 'members/base.html' %}

{% block content %}
<div>
    <h2 class="text-center">Change Your Password</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-secondary">Change Password</button>
    </form>
</div>
{% endblock %}

members/templates/members/main_menu_login.html
{% extends 'members/base.html' %}
{% load static %}

{% block pageTitle %}
{% endblock %}
{% block content %}
<p style="text-align:center">
<div class="h1">
  <a style="color:rgb(6, 6, 192)">
    <p style="font-size:40px">
      <h2 class="text-center">Main Menu Login</h2>
    </p>
  </a>
</div>
</p>
</br>

<form action="" method="POST" class="custom-form">
  {% csrf_token %}
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Username</label>
    <input type="text" class="form-control" name="username" aria-describedby="emailHelp" required>
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>

  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" name="password" required>
  </div>

  <input type="submit" value="Login" class="btn btn-secondary custom-btn">
  <a href="#" class="btn btn-link">No username? Register here; it's free and easy</a>
  <a class="btn btn-secondary" href="{% url 'members:register_user' %}">Register</a>
  <!-- <button type="button" class="btn btn-secondary">Register</button> -->
</form>

{% endblock %}

members/templates/members/register_user.html
{% extends 'members/base.html' %}
{% load static %}
{% block pageTitle %}
{% endblock %}
{% block content %}
{% if form.errors %}
    <div class="alert alert-warning alert-dismissable fade show" role="alert">
        There Was An Error On The Form.  One Or More Of The Fields Did Not Meet Validation Criteria
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
    </div>
{% endif %}

  <p style="text-align:center">
    <div class="h1">
      <a style="color:rgb(6, 6, 192)">
        <p style="font-size:40px">
          <h2>Register</h2>
        </p>
      </a>
    </div>
  </p>

  <div class="shadow p-4 mb-5 bg-body rounded">
      <form action="{% url 'members:register_user' %}" method=POST>
          {% csrf_token %}
          {% load widget_tweaks %}
          <!-- {{ form.as_p }} -->

          <div class="form-group">
           <!-- username is the default name of username in django forms -->
           {% render_field form.username type="text" class="form-control" id="exampleInputUsername" placeholder="Username" %}
         </div>

         <br/>
          <div class="form-group">
              <!-- first_name is the name by which first name is created in django forms -->
              {% render_field form.first_name class="form-control" placeholder="First Name" type="text" %}
          </div>

          <br/>
          <div class="form-group">
              <!-- last_name is the name by which last name is created in django forms -->
              {% render_field form.last_name type="text" class="form-control" placeholder="Last Name" %}
          </div>

          <br/>
          <div class="form-group">
            <!-- email is the name by which last name is created in django forms -->
            {% render_field form.email type="text" class="form-control" placeholder="email" %}
          </div>
        
          <br/>
          <div class="form-group">
              <!-- password1 is the default name of password in django forms -->
              {% render_field form.password1 type="password1" class="form-control" id="exampleInputPassword" placeholder="Password" %}
          </div>

          <br/>
          <div class="form-group">
            <!-- password2 is the default name of password in django forms -->
            {% render_field form.password2 type="password" class="form-control" id="exampleInputPassword" placeholder="Confirm Password" %}
        </div>

        <br/>
        <input type="submit" value="Register" class="btn btn-secondary">
        <a href="{% url 'members:main_menu_login' %}" class="btn btn-link">Already has an account? Please login.</a>
      </form>
  </div>
{% endblock %}

members/templates/members/update_user.html
{% extends 'members/base.html' %}
{% load static %}
{% block pageTitle %}
{% endblock %}
{% block content %}
{% if form.errors %}
    <div class="alert alert-warning alert-dismissable fade show" role="alert">
        There Was An Error On The Form.  One Or More Of The Fields Did Not Meet Validation Criteria
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
    </div>
{% endif %}

  <p style="text-align:center">
    <div class="h1">
      <a style="color:rgb(6, 6, 192)">
        <p style="font-size:40px">
          <h2>Update</h2>
        </p>
      </a>
    </div>
  </p>

  <div class="shadow p-4 mb-5 bg-body rounded">
      <form action="{% url 'members:update_user' %}" method=POST enctype="multipart/form-data">
          {% csrf_token %}
          {% load widget_tweaks %}
          <!-- {{ form.as_p }} -->

          <div class="form-group">
           <!-- username is the default name of username in django forms -->
           {% render_field user_form.username type="text" class="form-control" id="exampleInputUsername" placeholder="Username" %}
         </div>

         <br/>
          <div class="form-group">
              <!-- first_name is the name by which first name is created in django forms -->
              {% render_field user_form.first_name class="form-control" placeholder="First Name" type="text" %}
          </div>

          <br/>
          <div class="form-group">
              <!-- last_name is the name by which last name is created in django forms -->
              {% render_field user_form.last_name type="text" class="form-control" placeholder="Last Name" %}
          </div>

          <br/>
          <div class="form-group">
            <!-- email is the name by which last name is created in django forms -->
            {% render_field user_form.email type="text" class="form-control" placeholder="email" %}
          </div>
        
          <br/>
        {% if form.errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
              {% for field in form %}
              {{ field.errors }}
              {% endfor %}
    
              {{ form.non_field_errors }}
            </div>
            {% endif %}

        <br/>
        {{ profile_form.as_p }}
        <input type="submit" value="Update Profile" class="btn btn-secondary">
      </form>
  </div>
{% endblock %}